version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    #image: replace once the build is baked
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ../src:/var/www

  nginx:
    build:
      context: ./nginx
    #image: replace once the build is baked
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm